import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { ChakraProvider } from '@chakra-ui/react'

const font = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Table Chakra Ui',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={font.className}>
        <ChakraProvider>
          <main>
            {children}
          </main>
        </ChakraProvider>
        </body>
    </html>
  )
}
